# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/duke/Code/tick

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/duke/Code/tick

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/duke/Code/tick/CMakeFiles /Users/duke/Code/tick//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/duke/Code/tick/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tdl

# Build rule for target.
tdl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tdl
.PHONY : tdl

# fast build rule for target.
tdl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/build
.PHONY : tdl/fast

src/compiler/ast.o: src/compiler/ast.cpp.o
.PHONY : src/compiler/ast.o

# target to build an object file
src/compiler/ast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/compiler/ast.cpp.o
.PHONY : src/compiler/ast.cpp.o

src/compiler/ast.i: src/compiler/ast.cpp.i
.PHONY : src/compiler/ast.i

# target to preprocess a source file
src/compiler/ast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/compiler/ast.cpp.i
.PHONY : src/compiler/ast.cpp.i

src/compiler/ast.s: src/compiler/ast.cpp.s
.PHONY : src/compiler/ast.s

# target to generate assembly for a file
src/compiler/ast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/compiler/ast.cpp.s
.PHONY : src/compiler/ast.cpp.s

src/compiler/lexer.o: src/compiler/lexer.cpp.o
.PHONY : src/compiler/lexer.o

# target to build an object file
src/compiler/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/compiler/lexer.cpp.o
.PHONY : src/compiler/lexer.cpp.o

src/compiler/lexer.i: src/compiler/lexer.cpp.i
.PHONY : src/compiler/lexer.i

# target to preprocess a source file
src/compiler/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/compiler/lexer.cpp.i
.PHONY : src/compiler/lexer.cpp.i

src/compiler/lexer.s: src/compiler/lexer.cpp.s
.PHONY : src/compiler/lexer.s

# target to generate assembly for a file
src/compiler/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/compiler/lexer.cpp.s
.PHONY : src/compiler/lexer.cpp.s

src/compiler/parser.o: src/compiler/parser.cpp.o
.PHONY : src/compiler/parser.o

# target to build an object file
src/compiler/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/compiler/parser.cpp.o
.PHONY : src/compiler/parser.cpp.o

src/compiler/parser.i: src/compiler/parser.cpp.i
.PHONY : src/compiler/parser.i

# target to preprocess a source file
src/compiler/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/compiler/parser.cpp.i
.PHONY : src/compiler/parser.cpp.i

src/compiler/parser.s: src/compiler/parser.cpp.s
.PHONY : src/compiler/parser.s

# target to generate assembly for a file
src/compiler/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/compiler/parser.cpp.s
.PHONY : src/compiler/parser.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/runtime/dependency_analyzer.o: src/runtime/dependency_analyzer.cpp.o
.PHONY : src/runtime/dependency_analyzer.o

# target to build an object file
src/runtime/dependency_analyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/runtime/dependency_analyzer.cpp.o
.PHONY : src/runtime/dependency_analyzer.cpp.o

src/runtime/dependency_analyzer.i: src/runtime/dependency_analyzer.cpp.i
.PHONY : src/runtime/dependency_analyzer.i

# target to preprocess a source file
src/runtime/dependency_analyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/runtime/dependency_analyzer.cpp.i
.PHONY : src/runtime/dependency_analyzer.cpp.i

src/runtime/dependency_analyzer.s: src/runtime/dependency_analyzer.cpp.s
.PHONY : src/runtime/dependency_analyzer.s

# target to generate assembly for a file
src/runtime/dependency_analyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/runtime/dependency_analyzer.cpp.s
.PHONY : src/runtime/dependency_analyzer.cpp.s

src/runtime/executor.o: src/runtime/executor.cpp.o
.PHONY : src/runtime/executor.o

# target to build an object file
src/runtime/executor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/runtime/executor.cpp.o
.PHONY : src/runtime/executor.cpp.o

src/runtime/executor.i: src/runtime/executor.cpp.i
.PHONY : src/runtime/executor.i

# target to preprocess a source file
src/runtime/executor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/runtime/executor.cpp.i
.PHONY : src/runtime/executor.cpp.i

src/runtime/executor.s: src/runtime/executor.cpp.s
.PHONY : src/runtime/executor.s

# target to generate assembly for a file
src/runtime/executor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/runtime/executor.cpp.s
.PHONY : src/runtime/executor.cpp.s

src/runtime/scheduler.o: src/runtime/scheduler.cpp.o
.PHONY : src/runtime/scheduler.o

# target to build an object file
src/runtime/scheduler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/runtime/scheduler.cpp.o
.PHONY : src/runtime/scheduler.cpp.o

src/runtime/scheduler.i: src/runtime/scheduler.cpp.i
.PHONY : src/runtime/scheduler.i

# target to preprocess a source file
src/runtime/scheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/runtime/scheduler.cpp.i
.PHONY : src/runtime/scheduler.cpp.i

src/runtime/scheduler.s: src/runtime/scheduler.cpp.s
.PHONY : src/runtime/scheduler.s

# target to generate assembly for a file
src/runtime/scheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tdl.dir/build.make CMakeFiles/tdl.dir/src/runtime/scheduler.cpp.s
.PHONY : src/runtime/scheduler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... tdl"
	@echo "... src/compiler/ast.o"
	@echo "... src/compiler/ast.i"
	@echo "... src/compiler/ast.s"
	@echo "... src/compiler/lexer.o"
	@echo "... src/compiler/lexer.i"
	@echo "... src/compiler/lexer.s"
	@echo "... src/compiler/parser.o"
	@echo "... src/compiler/parser.i"
	@echo "... src/compiler/parser.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/runtime/dependency_analyzer.o"
	@echo "... src/runtime/dependency_analyzer.i"
	@echo "... src/runtime/dependency_analyzer.s"
	@echo "... src/runtime/executor.o"
	@echo "... src/runtime/executor.i"
	@echo "... src/runtime/executor.s"
	@echo "... src/runtime/scheduler.o"
	@echo "... src/runtime/scheduler.i"
	@echo "... src/runtime/scheduler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

